<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pipeline" nsURI="http://www.project.ase.polimi.it/pipeline"
    nsPrefix="pipeline">
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlows" lowerBound="1"
        upperBound="-1" eType="#//DataFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalDataFlows" upperBound="-1"
        eType="#//InternalDataFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputSources" lowerBound="1"
        upperBound="-1" eType="#//Source" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputFiles" upperBound="-1"
        eType="#//File" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" lowerBound="1"
        upperBound="-1" eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" lowerBound="1"
        upperBound="-1" eType="#//Schema" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="ID"/>
      <details key="figure" value="rounded"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//DataFlow" eOpposite="#//DataFlow/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//DataFlow" eOpposite="#//DataFlow/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="closedarrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//Format"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Task"
        eOpposite="#//Task/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Task"
        eOpposite="#//Task/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//Schema">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="ellipse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//InternalDataFlow"
        eOpposite="#//InternalDataFlow/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" eType="#//InternalDataFlow"
        eOpposite="#//InternalDataFlow/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalDataFlow">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="arrow"/>
      <details key="style" value="dash"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//Format"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Operation"
        eOpposite="#//Operation/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Operation"
        eOpposite="#//Operation/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intDFschema" lowerBound="1"
        eType="#//Schema">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.placement" value="none"/>
      <details key="figure" value="rounded"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Attribute"
        eOpposite="#//Attribute/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Attribute"
        eOpposite="#//Attribute/next"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" lowerBound="1"
        upperBound="-1" eType="#//Import" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="CleaningTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" lowerBound="1"
        upperBound="-1" eType="#//CleaningOperation" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyzes" lowerBound="1"
        upperBound="-1" eType="#//AnalysisOperation" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisualizationTask" eSuperTypes="#//Task"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExportTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exports" lowerBound="1"
        upperBound="-1" eType="#//Export" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.text" value="Import"/>
      <details key="figure" value="ellipse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readsFrom" lowerBound="1"
        eType="#//Source" eOpposite="#//Source/linkedTo">
      <eAnnotations source="gmf.link">
        <details key="width" value="2"/>
        <details key="target.decoration" value="square"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impUses" lowerBound="1"
        eType="#//Schema">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="arrow"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Export">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.text" value="Export"/>
      <details key="figure" value="ellipse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generates" lowerBound="1"
        eType="#//File" eOpposite="#//File/comesFrom">
      <eAnnotations source="gmf.link">
        <details key="width" value="2"/>
        <details key="target.decoration" value="square"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expUses" lowerBound="1"
        eType="#//Schema">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="arrow"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefined" eSuperTypes="#//CleaningOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Source">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedTo" lowerBound="1"
        eType="#//Import" eOpposite="#//Import/readsFrom"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comesFrom" lowerBound="1"
        eType="#//Export" eOpposite="#//Export/generates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CleaningOperation" abstract="true" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisOperation" abstract="true" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Descriptive" eSuperTypes="#//AnalysisOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Classification" eSuperTypes="#//AnalysisOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Predictive" eSuperTypes="#//AnalysisOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Clustering" eSuperTypes="#//AnalysisOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="k" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predefined" eSuperTypes="#//CleaningOperation"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Format">
    <eLiterals name="txt"/>
    <eLiterals name="csv"/>
    <eLiterals name="json"/>
    <eLiterals name="XML"/>
  </eClassifiers>
</ecore:EPackage>
