<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pipeline" nsURI="http://www.project.ase.polimi.it/pipeline"
    nsPrefix="pipeline">
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFlows" lowerBound="1"
        upperBound="-1" eType="#//DataFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1" upperBound="-1"
        eType="#//Task" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalDataFlows" upperBound="-1"
        eType="#//InternalDataFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" lowerBound="1"
        upperBound="-1" eType="#//Source" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//File" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" lowerBound="1"
        upperBound="-1" eType="#//Schema" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="charts" upperBound="-1"
        eType="#//Chart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="ID"/>
      <details key="figure" value="rounded"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//DataFlow" eOpposite="#//DataFlow/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//DataFlow" eOpposite="#//DataFlow/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="filledclosedarrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//Format"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Task"
        eOpposite="#//Task/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Task"
        eOpposite="#//Task/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//Schema">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="arrow"/>
        <details key="tool.name" value="DFSchema"/>
        <details key="style" value="dot"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" eType="#//InternalDataFlow"
        eOpposite="#//InternalDataFlow/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" eType="#//InternalDataFlow"
        eOpposite="#//InternalDataFlow/source"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//SimpleAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalDataFlow">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="filledclosedarrow"/>
      <details key="style" value="dash"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="#//Format"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Operation"
        eOpposite="#//Operation/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Operation"
        eOpposite="#//Operation/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//Schema">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dot"/>
        <details key="tool.name" value="InternalDFSchema"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.placement" value="none"/>
      <details key="figure" value="rounded"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Attribute"
        eOpposite="#//Attribute/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Attribute"
        eOpposite="#//Attribute/next"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importOperations" lowerBound="1"
        upperBound="-1" eType="#//ImportOperation" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrationTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute">
      <eAnnotations source="gmf.link">
        <details key="width" value="2"/>
        <details key="target.decoration" value="closedarrow"/>
        <details key="tool.name" value="IntegrationAttributes"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CleaningTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cleaningOperations" lowerBound="1"
        upperBound="-1" eType="#//CleaningOperation" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="analysisOperations" lowerBound="1"
        upperBound="-1" eType="#//AnalysisOperation" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisualizationTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visualizationOperations"
        lowerBound="1" upperBound="-1" eType="#//VisualizationOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exportOperations" lowerBound="1"
        upperBound="-1" eType="#//ExportOperation" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportOperation">
    <eAnnotations source="gmf.node">
      <details key="label" value="ID"/>
      <details key="label.text" value="Import"/>
      <details key="figure" value="ellipse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="read" lowerBound="1" eType="#//Source"
        eOpposite="#//Source/linkedTo">
      <eAnnotations source="gmf.link">
        <details key="width" value="2"/>
        <details key="target.decoration" value="square"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="use" lowerBound="1" eType="#//Schema">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="arrow"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportOperation">
    <eAnnotations source="gmf.node">
      <details key="label" value="ID"/>
      <details key="label.text" value="Export"/>
      <details key="figure" value="ellipse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="use" lowerBound="1" eType="#//Schema">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="arrow"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="write" lowerBound="1" eType="#//File"
        eOpposite="#//File/comesFrom">
      <eAnnotations source="gmf.link">
        <details key="width" value="2"/>
        <details key="target.decoration" value="filledsquare"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDefinedCleaningOperation" eSuperTypes="#//CleaningOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedTo" lowerBound="1"
        eType="#//ImportOperation" eOpposite="#//ImportOperation/read"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comesFrom" lowerBound="1"
        eType="#//ExportOperation" eOpposite="#//ExportOperation/write"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart">
    <eAnnotations source="gmf.node">
      <details key="label" value="title"/>
      <details key="figure" value="rounded"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="#//Size"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ChartType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axes" lowerBound="1" upperBound="-1"
        eType="#//SimpleAttribute">
      <eAnnotations source="gmf.link">
        <details key="width" value="1"/>
        <details key="target.decoration" value="closedarrow"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CleaningOperation" abstract="true" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisOperation" abstract="true" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptiveAnalysisOperation" eSuperTypes="#//AnalysisOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DescriptiveOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassificationAnalysisOperation" eSuperTypes="#//AnalysisOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ClassificationOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredictiveAnalysisOperation" eSuperTypes="#//AnalysisOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PredictiveOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClusteringAnalysisOperation" eSuperTypes="#//AnalysisOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ClusteringOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="k" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredefinedCleaningOperation" eSuperTypes="#//CleaningOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PredefinedOperation"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexAttribute" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PredefinedOperation">
    <eLiterals name="removeNulls"/>
    <eLiterals name="removeNegative" value="1"/>
    <eLiterals name="round" value="2"/>
    <eLiterals name="removeColumn" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClusteringOperation">
    <eLiterals name="kMeans"/>
    <eLiterals name="Hierarchical" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassificationOperation">
    <eLiterals name="LogisticRegression"/>
    <eLiterals name="LDA" value="1"/>
    <eLiterals name="QDA" value="2"/>
    <eLiterals name="KNN" value="3"/>
    <eLiterals name="SVM" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PredictiveOperation">
    <eLiterals name="SimpleRegression"/>
    <eLiterals name="MultipleLinRegr" value="1"/>
    <eLiterals name="RandomForests" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DescriptiveOperation">
    <eLiterals name="Histogram"/>
    <eLiterals name="Boxplot" value="1"/>
    <eLiterals name="PieChart" value="2"/>
    <eLiterals name="ScatterPlot" value="4"/>
    <eLiterals name="ViewData" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChartType">
    <eLiterals name="Column"/>
    <eLiterals name="Line"/>
    <eLiterals name="Pie"/>
    <eLiterals name="Bar"/>
    <eLiterals name="Area"/>
    <eLiterals name="Scatter"/>
    <eLiterals name="Surface"/>
    <eLiterals name="Radar"/>
    <eLiterals name="Histogram"/>
    <eLiterals name="BoxPlot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Format">
    <eLiterals name="CSV"/>
    <eLiterals name="JSON" value="1"/>
    <eLiterals name="TXT" value="2"/>
    <eLiterals name="XML" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Size">
    <eLiterals name="Small"/>
    <eLiterals name="Medium" value="1"/>
    <eLiterals name="Large" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="mString"/>
    <eLiterals name="mInteger" value="1"/>
    <eLiterals name="mDouble" value="2"/>
    <eLiterals name="mBoolean" value="3"/>
    <eLiterals name="mDate" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisualizationOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chart" lowerBound="1" eType="#//Chart"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
